### ISSUE TITLE
change package name

### ISSUE THREAD

**Issue by njtierney** [njtierney/yahtsee#1]
It isn't specific to malaria 

It is about fitting hierarchical models of a certain standard form

It will initially be built to work with INLA, but could work with `gam` and others as well.

Possible ideas:

- `hits`
- `echelon`
- `tiers`
- `tshier`
-  `hierarchies`
- `hierarchts`

**Comment by goldingn** [comment]
Haha, I like `tiers`. But only because people will assume you named it after yourself.

**Comment by goldingn** [comment]
getting the 'time series' aspect in there would be good - this is only one type of hierarchical model, so anything based only on the hierarchical nature would be confusingly broad.

**Comment by njtierney** [comment]
It did occur to me that `tiers` could be self naming and that this would be amusing.

Some more ideas:

- `tsep` (anagram of "step", like a hierarchy - also gets in the `ts` part of time series)
- `tspop` (population data time series stuff?)
- `bahts` (Bayesian Approaches to Hierarchical Time Series?)
- `sahts` (Some/Statistical Approaches to Hierarchical Time Series?)
- `hoots` (Hierarchical ..... something something Time Series)
- `heists` (Hierarchical .... Time Series?)

This website is fun for searching words starting with a letter and ending in others.

https://www.wordhippo.com/what-is/word-finder-unscrambler.html

Turns out that is popular for cross worders!

**Comment by goldingn** [comment]
Ending with 'Global Health Timeseries' gives ght or ghts at the end, which opens up a bunch of potential puns.

The models aren't specific to global health. I could find a nicer g to go before Hierarchical Timeseries though.

**Comment by goldingn** [comment]
Models in Global Health Timeseries' = might?

**Comment by njtierney** [comment]
yup, `might` sounds good to me. I think that `mightr` would be marginally better in that it is more google-able.

**Comment by goldingn** [comment]
Yeah, good point about googlability. Though I always find myself grinding my teeth whenever I see an R package with R tacked on the end.

**Comment by njtierney** [comment]
Package named changed to `yahtsee`
