### ISSUE TITLE
make Intercept term optional

### ISSUE THREAD

**Issue by njtierney** [njtierney/yahtsee#14]
Currently the intercept term is added to the model automatically, but we could have a way to have no intercept by doing the following:

1. detect `0` in a formula (e.g., `y ~ 0 + beta`)
2. Replace `Intercept` with `0` in the inla modelling step

Or something similar

**Comment by mitchelloharawild** [comment]
If the model is written with the fabletools framework, there is a helper special for handling xregs using the standard R formula interface:
https://github.com/tidyverts/fabletools/blob/4441118552964f7c051d50ac0c3dad4058d556ec/R/specials.R#L21-L73

**Comment by njtierney** [comment]
Neat! Silly question - what is an `xreg`?

**Comment by mitchelloharawild** [comment]
An exogenous regressor :smile:
